create table if not exists tutors (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text,
  whatsapp text,
  email text,
  address text,
  emergency_contact text,
  created_at timestamptz not null default now()
);

create table if not exists pets (
  id bigint generated by default as identity primary key,
  tutor_id bigint references tutors(id) on delete cascade,
  name text not null,
  breed text,
  size text,
  sex text,
  weight numeric,
  birth_date date,
  behavior text,
  food_restrictions text,
  medications text,
  important_notes text,
  veterinarian text,
  photo_url text,
  created_at timestamptz not null default now()
);

create table if not exists reservations (
  id bigint generated by default as identity primary key,
  pet_id bigint references pets(id) on delete set null,
  tutor_name text not null,
  phone text not null,
  email text,
  pet_name text not null,
  breed text,
  size text,
  service text not null,
  entry_date date not null,
  exit_date date,
  expected_time text,
  notes text,
  status text not null default 'Aguardando aprovacao',
  created_at timestamptz not null default now()
);

create or replace view pet_options as
select
  pets.id,
  pets.name,
  pets.breed,
  pets.size,
  tutors.full_name as tutor_name,
  tutors.phone as tutor_phone,
  tutors.email as tutor_email
from pets
left join tutors on tutors.id = pets.tutor_id;

insert into tutors (full_name, phone, whatsapp, email, address, emergency_contact)
values ('Mariana Alves', '11984130296', '11984130296', 'mariana@email.com', 'Rua das Flores, 120', 'Carina - 11977552805')
on conflict do nothing;

insert into pets (tutor_id, name, breed, size, sex)
select id, 'Luna', 'Golden Retriever', 'Grande', 'Femea'
from tutors
where full_name = 'Mariana Alves'
limit 1
on conflict do nothing;
