-- =====================================================================
-- Scolt&Cia - Creche Pet  |  Recriacao completa do banco (Supabase / Postgres)
-- ---------------------------------------------------------------------
-- COMO USAR:
--   1. Crie um novo projeto no Supabase.
--   2. Abra SQL Editor > New query.
--   3. Cole TODO este arquivo e clique em "Run".
--   4. Copie as chaves em Project Settings > API e configure no .env / Vercel:
--        NEXT_PUBLIC_SUPABASE_URL
--        NEXT_PUBLIC_SUPABASE_ANON_KEY
--        SUPABASE_SERVICE_ROLE_KEY
--
-- O script e IDEMPOTENTE: pode ser executado novamente sem apagar dados.
-- Toda a aplicacao acessa os dados pelo SERVICE ROLE (server-side), que
-- ignora o RLS. O RLS abaixo bloqueia acesso publico (anon) as tabelas.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. TABELAS
-- ---------------------------------------------------------------------

create table if not exists tutors (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text,
  whatsapp text,
  email text,
  address text,
  emergency_contact text,
  created_at timestamptz not null default now()
);

create table if not exists app_users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  role text not null default 'equipe' check (role in ('admin', 'equipe', 'tutor')),
  entities jsonb not null default '["creche"]'::jsonb,
  permissions jsonb,
  password_salt text not null,
  password_hash text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists pets (
  id bigint generated by default as identity primary key,
  tutor_id bigint references tutors(id) on delete cascade,
  name text not null,
  breed text,
  size text,
  sex text,
  weight numeric,
  birth_date date,
  behavior text,
  food_restrictions text,
  medications text,
  important_notes text,
  veterinarian text,
  photo_url text,
  service_prices jsonb,
  created_at timestamptz not null default now()
);

create table if not exists pet_tutors (
  pet_id bigint not null references pets(id) on delete cascade,
  tutor_id bigint not null references tutors(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (pet_id, tutor_id)
);

create table if not exists reservations (
  id bigint generated by default as identity primary key,
  pet_id bigint references pets(id) on delete set null,
  tutor_name text not null,
  phone text not null,
  email text,
  pet_name text not null,
  breed text,
  size text,
  service text not null,
  entry_date date not null,
  exit_date date,
  expected_time text,
  exit_time text,
  daily_rate numeric,
  notes text,
  status text not null default 'Aguardando aprovacao',
  created_at timestamptz not null default now()
);

create table if not exists daycare_settings (
  id bigint primary key default 1,
  max_capacity integer not null default 20,
  updated_at timestamptz not null default now(),
  constraint one_daycare_settings_row check (id = 1)
);

create table if not exists admin_records (
  id bigint generated by default as identity primary key,
  module_key text not null,
  title text not null,
  status text not null default 'Ativo',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 2. INDICES
-- ---------------------------------------------------------------------

create index if not exists admin_records_module_key_idx on admin_records(module_key);
create index if not exists pet_tutors_tutor_id_idx on pet_tutors(tutor_id);
create index if not exists pets_tutor_id_idx on pets(tutor_id);
create index if not exists reservations_status_idx on reservations(status);
create index if not exists reservations_entry_date_idx on reservations(entry_date);

-- Backfill: garante o vinculo N:N a partir do tutor_id legado dos pets.
insert into pet_tutors (pet_id, tutor_id)
select id, tutor_id
from pets
where tutor_id is not null
on conflict do nothing;

-- ---------------------------------------------------------------------
-- 3. VIEW pet_options (consumida por lib/data.ts -> from("pet_options"))
--    Agrega o(s) tutor(es) de cada pet via tabela N:N pet_tutors.
-- ---------------------------------------------------------------------

alter table pets add column if not exists service_prices jsonb;
alter table reservations add column if not exists daily_rate numeric;

create or replace view pet_options as
select
  pets.id,
  pets.name,
  pets.breed,
  pets.size,
  coalesce(tutor_links.tutor_names, tutors.full_name) as tutor_name,
  coalesce(tutor_links.tutor_phone, tutors.phone) as tutor_phone,
  coalesce(tutor_links.tutor_email, tutors.email) as tutor_email,
  pets.birth_date,
  pets.photo_url,
  pets.created_at,
  pets.sex,
  pets.weight,
  pets.behavior,
  pets.food_restrictions,
  pets.medications,
  pets.important_notes,
  pets.veterinarian,
  pets.service_prices,
  tutors.id as tutor_id,
  coalesce(tutor_links.tutor_ids, case when tutors.id is null then array[]::bigint[] else array[tutors.id] end) as tutor_ids,
  coalesce(tutor_links.tutor_address, tutors.address) as tutor_address
from pets
left join tutors on tutors.id = pets.tutor_id
left join lateral (
  select
    array_agg(tutors_linked.id order by tutors_linked.full_name) as tutor_ids,
    string_agg(tutors_linked.full_name, ', ' order by tutors_linked.full_name) as tutor_names,
    (array_agg(tutors_linked.phone order by tutors_linked.full_name))[1] as tutor_phone,
    (array_agg(tutors_linked.email order by tutors_linked.full_name))[1] as tutor_email,
    string_agg(tutors_linked.address, ' | ' order by tutors_linked.full_name) as tutor_address
  from pet_tutors
  join tutors tutors_linked on tutors_linked.id = pet_tutors.tutor_id
  where pet_tutors.pet_id = pets.id
) tutor_links on true;

-- A view respeita o RLS das tabelas-base (Postgres 15+, padrao no Supabase).
-- Assim o anon nao consegue ler dados de pets/tutores atraves dela.
alter view pet_options set (security_invoker = on);

-- ---------------------------------------------------------------------
-- 4. SEGURANCA (RLS)
--    Habilita RLS SEM policies => nega todo acesso de anon/authenticated.
--    O app usa o SERVICE ROLE (server-side), que ignora o RLS.
--    Sem isso, as tabelas (incluindo hashes de senha em app_users!)
--    ficariam publicamente acessiveis via PostgREST com a chave anon.
-- ---------------------------------------------------------------------

alter table tutors            enable row level security;
alter table app_users         enable row level security;
alter table pets              enable row level security;
alter table pet_tutors        enable row level security;
alter table reservations      enable row level security;
alter table daycare_settings  enable row level security;
alter table admin_records     enable row level security;

-- Remove qualquer acesso direto de anon/authenticated a view agregada.
revoke all on pet_options from anon, authenticated;

-- ---------------------------------------------------------------------
-- 5. MIGRACOES IDEMPOTENTES PARA BANCOS EXISTENTES
--    Garante colunas criadas em versoes posteriores antes dos seeds.
-- ---------------------------------------------------------------------

alter table app_users add column if not exists tutor_id bigint references tutors(id) on delete set null;
alter table app_users add column if not exists entities jsonb not null default '["creche"]'::jsonb;
alter table app_users add column if not exists permissions jsonb;
alter table reservations add column if not exists exit_time text;
alter table reservations add column if not exists daily_rate numeric;
alter table pets add column if not exists allergies text;
alter table pets add column if not exists microchip text;
alter table pets add column if not exists neutered boolean;
alter table pets add column if not exists cover_url text;
alter table pets add column if not exists service_prices jsonb;

-- ---------------------------------------------------------------------
-- 6. ADMIN INICIAL
--    Criado automaticamente para facilitar o primeiro acesso ao painel.
--    E-mail: lucasalmeidapedroso@gmail.com
--    Senha inicial: !Levi@2023
--    O app compara por scrypt usando password_salt + password_hash.
-- ---------------------------------------------------------------------

insert into app_users (name, email, role, entities, permissions, password_salt, password_hash, is_active)
values (
  'Lucas Pedroso',
  'lucasalmeidapedroso@gmail.com',
  'admin',
  '["creche", "hotel"]'::jsonb,
  null,
  'scoltcia-lucas-2026',
  '293cadd0d05b6a718089980f7256eb44745f339733cc8a4b01be2410f8340ec1937bc3447e09dde1034a9c61213c3220b361587bb4b9acf40e93cc4385702084',
  true
)
on conflict (email) do update set
  name = excluded.name,
  role = excluded.role,
  entities = excluded.entities,
  permissions = excluded.permissions,
  password_salt = excluded.password_salt,
  password_hash = excluded.password_hash,
  is_active = true;

-- ---------------------------------------------------------------------
-- 7. SEED - configuracao da creche (linha unica, id = 1)
-- ---------------------------------------------------------------------

insert into daycare_settings (id, max_capacity)
values (1, 20)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------
-- 8. AREA DO TUTOR - tabelas do portal de acompanhamento
-- ---------------------------------------------------------------------
-- Toda a Area do Tutor le dados reais por aqui (via service role).
-- 
-- =====================================================================

-- Presenca atual do pet (status "agora" no dashboard).
create table if not exists pet_presence (
  pet_id bigint primary key references pets(id) on delete cascade,
  present boolean not null default false,
  location text,
  activity text,
  last_visit text,
  updated_at timestamptz not null default now()
);

-- Tracos de personalidade configuraveis.
create table if not exists pet_traits (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  emoji text,
  label text not null,
  created_at timestamptz not null default now()
);

-- Timeline (diario cronologico do dia).
create table if not exists timeline_events (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  event_date date not null default current_date,
  event_time text not null,
  icon text,
  title text not null,
  detail text,
  type text not null default 'play',
  created_at timestamptz not null default now()
);

-- Galeria de fotos.
create table if not exists pet_photos (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  url text not null,
  caption text,
  taken_at timestamptz not null default now(),
  registered_by text,
  place text,
  period text,
  favorite boolean not null default false,
  created_at timestamptz not null default now()
);

-- Galeria de videos.
create table if not exists pet_videos (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  thumb_url text,
  video_url text,
  caption text,
  recorded_at timestamptz not null default now(),
  duration text,
  created_at timestamptz not null default now()
);

-- Carteira de vacinacao.
create table if not exists vaccines (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  name text not null,
  applied_date date,
  valid_until date,
  required boolean not null default false,
  attachment_url text,
  created_at timestamptz not null default now()
);

-- Plano/pacotes do tutor (resumo financeiro).
create table if not exists tutor_billing (
  tutor_id bigint primary key references tutors(id) on delete cascade,
  plan text,
  monthly_value numeric not null default 0,
  packages_left integer not null default 0,
  package_total integer not null default 0,
  next_due date,
  updated_at timestamptz not null default now()
);

-- Historico de pagamentos / notas.
create table if not exists invoices (
  id bigint generated by default as identity primary key,
  tutor_id bigint not null references tutors(id) on delete cascade,
  invoice_date date not null default current_date,
  description text not null,
  method text not null default 'PIX' check (method in ('PIX', 'Cartao', 'Boleto')),
  value numeric not null default 0,
  status text not null default 'Pendente' check (status in ('Pago', 'Pendente', 'Atrasado')),
  receipt_url text,
  created_at timestamptz not null default now()
);

-- Chat entre tutor e equipe (vinculado ao pet).
create table if not exists pet_messages (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  sender text not null default 'team' check (sender in ('tutor', 'team')),
  author text,
  body text not null,
  created_at timestamptz not null default now()
);

-- Notificacoes do tutor.
create table if not exists tutor_notifications (
  id bigint generated by default as identity primary key,
  tutor_id bigint not null references tutors(id) on delete cascade,
  icon text,
  body text not null,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

-- Relatorio diario.
create table if not exists daily_reports (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  report_date date not null default current_date,
  summary text,
  food text,
  hydration text,
  rest text,
  social text,
  mood text,
  occurrences text,
  responsible text,
  created_at timestamptz not null default now(),
  unique (pet_id, report_date)
);

-- Conquistas / medalhas.
create table if not exists pet_achievements (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  icon text,
  title text not null,
  description text,
  earned boolean not null default false,
  earned_at date,
  created_at timestamptz not null default now()
);

-- Linha do tempo da vida (momentos marcantes).
create table if not exists life_moments (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  icon text,
  title text not null,
  moment_date text,
  description text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

-- Historico de peso.
create table if not exists pet_weights (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  label text not null,
  weight numeric not null,
  recorded_on date,
  created_at timestamptz not null default now()
);

-- Resumos / insights gerados pela IA.
create table if not exists ai_insights (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  period text not null default 'Semana',
  body text not null,
  created_at timestamptz not null default now()
);

-- Avisos/comunicados gerais da creche.
create table if not exists announcements (
  id bigint generated by default as identity primary key,
  icon text,
  title text not null,
  body text,
  published_at timestamptz not null default now()
);

-- Indices
create index if not exists timeline_events_pet_idx on timeline_events(pet_id, event_date);
create index if not exists pet_photos_pet_idx on pet_photos(pet_id);
create index if not exists pet_videos_pet_idx on pet_videos(pet_id);
create index if not exists vaccines_pet_idx on vaccines(pet_id);
create index if not exists invoices_tutor_idx on invoices(tutor_id);
create index if not exists pet_messages_pet_idx on pet_messages(pet_id, created_at);
create index if not exists tutor_notifications_tutor_idx on tutor_notifications(tutor_id, read);
create index if not exists daily_reports_pet_idx on daily_reports(pet_id, report_date);
create index if not exists app_users_tutor_id_idx on app_users(tutor_id);

-- RLS (nega anon; service role ignora). Igual ao restante do schema.
alter table pet_presence        enable row level security;
alter table pet_traits          enable row level security;
alter table timeline_events     enable row level security;
alter table pet_photos          enable row level security;
alter table pet_videos          enable row level security;
alter table vaccines            enable row level security;
alter table tutor_billing       enable row level security;
alter table invoices            enable row level security;
alter table pet_messages        enable row level security;
alter table tutor_notifications enable row level security;
alter table daily_reports       enable row level security;
alter table pet_achievements    enable row level security;
alter table life_moments        enable row level security;
alter table pet_weights         enable row level security;
alter table ai_insights         enable row level security;
alter table announcements       enable row level security;

-- =====================================================================
-- 8. AREA DO TUTOR
--    Contas de tutor devem ser criadas pelo painel/admin ou por script privado,
--    evitando senhas versionadas no repositorio.
-- =====================================================================
