-- =====================================================================
-- Scolt&Cia - Creche Pet  |  Recriacao completa do banco (Supabase / Postgres)
-- ---------------------------------------------------------------------
-- COMO USAR:
--   1. Crie um novo projeto no Supabase.
--   2. Abra SQL Editor > New query.
--   3. Cole TODO este arquivo e clique em "Run".
--   4. Copie as chaves em Project Settings > API e configure no .env / Vercel:
--        NEXT_PUBLIC_SUPABASE_URL
--        NEXT_PUBLIC_SUPABASE_ANON_KEY
--        SUPABASE_SERVICE_ROLE_KEY
--
-- O script e IDEMPOTENTE: pode ser executado novamente sem apagar dados.
-- Toda a aplicacao acessa os dados pelo SERVICE ROLE (server-side), que
-- ignora o RLS. O RLS abaixo bloqueia acesso publico (anon) as tabelas.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. TABELAS
-- ---------------------------------------------------------------------

create table if not exists tutors (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text,
  whatsapp text,
  email text,
  address text,
  emergency_contact text,
  created_at timestamptz not null default now()
);

create table if not exists app_users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  role text not null default 'equipe' check (role in ('admin', 'equipe', 'tutor')),
  password_salt text not null,
  password_hash text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists pets (
  id bigint generated by default as identity primary key,
  tutor_id bigint references tutors(id) on delete cascade,
  name text not null,
  breed text,
  size text,
  sex text,
  weight numeric,
  birth_date date,
  behavior text,
  food_restrictions text,
  medications text,
  important_notes text,
  veterinarian text,
  photo_url text,
  created_at timestamptz not null default now()
);

create table if not exists pet_tutors (
  pet_id bigint not null references pets(id) on delete cascade,
  tutor_id bigint not null references tutors(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (pet_id, tutor_id)
);

create table if not exists reservations (
  id bigint generated by default as identity primary key,
  pet_id bigint references pets(id) on delete set null,
  tutor_name text not null,
  phone text not null,
  email text,
  pet_name text not null,
  breed text,
  size text,
  service text not null,
  entry_date date not null,
  exit_date date,
  expected_time text,
  notes text,
  status text not null default 'Aguardando aprovacao',
  created_at timestamptz not null default now()
);

create table if not exists daycare_settings (
  id bigint primary key default 1,
  max_capacity integer not null default 20,
  updated_at timestamptz not null default now(),
  constraint one_daycare_settings_row check (id = 1)
);

create table if not exists admin_records (
  id bigint generated by default as identity primary key,
  module_key text not null,
  title text not null,
  status text not null default 'Ativo',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 2. INDICES
-- ---------------------------------------------------------------------

create index if not exists admin_records_module_key_idx on admin_records(module_key);
create index if not exists pet_tutors_tutor_id_idx on pet_tutors(tutor_id);
create index if not exists pets_tutor_id_idx on pets(tutor_id);
create index if not exists reservations_status_idx on reservations(status);
create index if not exists reservations_entry_date_idx on reservations(entry_date);

-- Backfill: garante o vinculo N:N a partir do tutor_id legado dos pets.
insert into pet_tutors (pet_id, tutor_id)
select id, tutor_id
from pets
where tutor_id is not null
on conflict do nothing;

-- ---------------------------------------------------------------------
-- 3. VIEW pet_options (consumida por lib/data.ts -> from("pet_options"))
--    Agrega o(s) tutor(es) de cada pet via tabela N:N pet_tutors.
-- ---------------------------------------------------------------------

create or replace view pet_options as
select
  pets.id,
  pets.name,
  pets.breed,
  pets.size,
  coalesce(tutor_links.tutor_names, tutors.full_name) as tutor_name,
  coalesce(tutor_links.tutor_phone, tutors.phone) as tutor_phone,
  coalesce(tutor_links.tutor_email, tutors.email) as tutor_email,
  pets.birth_date,
  pets.photo_url,
  pets.created_at,
  pets.sex,
  pets.weight,
  pets.behavior,
  pets.food_restrictions,
  pets.medications,
  pets.important_notes,
  pets.veterinarian,
  tutors.id as tutor_id,
  coalesce(tutor_links.tutor_ids, case when tutors.id is null then array[]::bigint[] else array[tutors.id] end) as tutor_ids,
  coalesce(tutor_links.tutor_address, tutors.address) as tutor_address
from pets
left join tutors on tutors.id = pets.tutor_id
left join lateral (
  select
    array_agg(tutors_linked.id order by tutors_linked.full_name) as tutor_ids,
    string_agg(tutors_linked.full_name, ', ' order by tutors_linked.full_name) as tutor_names,
    (array_agg(tutors_linked.phone order by tutors_linked.full_name))[1] as tutor_phone,
    (array_agg(tutors_linked.email order by tutors_linked.full_name))[1] as tutor_email,
    string_agg(tutors_linked.address, ' | ' order by tutors_linked.full_name) as tutor_address
  from pet_tutors
  join tutors tutors_linked on tutors_linked.id = pet_tutors.tutor_id
  where pet_tutors.pet_id = pets.id
) tutor_links on true;

-- A view respeita o RLS das tabelas-base (Postgres 15+, padrao no Supabase).
-- Assim o anon nao consegue ler dados de pets/tutores atraves dela.
alter view pet_options set (security_invoker = on);

-- ---------------------------------------------------------------------
-- 4. SEGURANCA (RLS)
--    Habilita RLS SEM policies => nega todo acesso de anon/authenticated.
--    O app usa o SERVICE ROLE (server-side), que ignora o RLS.
--    Sem isso, as tabelas (incluindo hashes de senha em app_users!)
--    ficariam publicamente acessiveis via PostgREST com a chave anon.
-- ---------------------------------------------------------------------

alter table tutors            enable row level security;
alter table app_users         enable row level security;
alter table pets              enable row level security;
alter table pet_tutors        enable row level security;
alter table reservations      enable row level security;
alter table daycare_settings  enable row level security;
alter table admin_records     enable row level security;

-- Remove qualquer acesso direto de anon/authenticated a view agregada.
revoke all on pet_options from anon, authenticated;

-- ---------------------------------------------------------------------
-- 5. SEED - usuario administrador inicial
--    Login do painel /admin:
--      e-mail: lucasalmeidapedroso@gmail.com
--      senha:  !Levi@2023
--    (hash scrypt 64 bytes do salt abaixo - validado contra lib/auth.ts)
-- ---------------------------------------------------------------------

insert into app_users (name, email, role, password_salt, password_hash, is_active)
values (
  'Lucas Pedroso',
  'lucasalmeidapedroso@gmail.com',
  'admin',
  'scoltcia-lucas-2026',
  '293cadd0d05b6a718089980f7256eb44745f339733cc8a4b01be2410f8340ec1937bc3447e09dde1034a9c61213c3220b361587bb4b9acf40e93cc4385702084',
  true
)
on conflict (email) do update set
  name = excluded.name,
  role = excluded.role,
  password_salt = excluded.password_salt,
  password_hash = excluded.password_hash,
  is_active = true;

-- ---------------------------------------------------------------------
-- 6. SEED - configuracao da creche (linha unica, id = 1)
-- ---------------------------------------------------------------------

insert into daycare_settings (id, max_capacity)
values (1, 20)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------
-- 7. SEED - dados de exemplo (opcional)
--    Um tutor + um pet para validar a tela de reserva imediatamente.
--    Pode remover este bloco em producao sem afetar o funcionamento.
-- ---------------------------------------------------------------------

insert into tutors (full_name, phone, whatsapp, email, address, emergency_contact)
select 'Mariana Alves', '11984130296', '11984130296', 'mariana@email.com', 'Rua das Flores, 120', 'Carina - 11977552805'
where not exists (
  select 1 from tutors where email = 'mariana@email.com'
);

insert into pets (tutor_id, name, breed, size, sex)
select id, 'Luna', 'Golden Retriever', 'Grande', 'Femea'
from tutors
where full_name = 'Mariana Alves'
and not exists (
  select 1 from pets
  where pets.name = 'Luna'
  and pets.tutor_id = tutors.id
)
limit 1
on conflict do nothing;

-- Re-sincroniza o vinculo N:N apos o seed.
insert into pet_tutors (pet_id, tutor_id)
select id, tutor_id
from pets
where tutor_id is not null
on conflict do nothing;

-- =====================================================================
-- 8. AREA DO TUTOR - tabelas do portal de acompanhamento
-- ---------------------------------------------------------------------
-- Mapeiam 1:1 com lib/tutor-demo.ts. Toda a Area do Tutor passa a poder
-- ler dados reais por aqui (via service role) mantendo o fallback demo.
-- =====================================================================

-- Vincula um usuario (login) ao cadastro de tutor e habilita o role tutor.
alter table app_users add column if not exists tutor_id bigint references tutors(id) on delete set null;
-- Campos extras do pet usados na Area do Tutor (aba Meu Pet).
alter table pets add column if not exists allergies text;
alter table pets add column if not exists microchip text;
alter table pets add column if not exists neutered boolean;
alter table pets add column if not exists cover_url text;

-- Presenca atual do pet (status "agora" no dashboard).
create table if not exists pet_presence (
  pet_id bigint primary key references pets(id) on delete cascade,
  present boolean not null default false,
  location text,
  activity text,
  last_visit text,
  updated_at timestamptz not null default now()
);

-- Tracos de personalidade configuraveis.
create table if not exists pet_traits (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  emoji text,
  label text not null,
  created_at timestamptz not null default now()
);

-- Timeline (diario cronologico do dia).
create table if not exists timeline_events (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  event_date date not null default current_date,
  event_time text not null,
  icon text,
  title text not null,
  detail text,
  type text not null default 'play',
  created_at timestamptz not null default now()
);

-- Galeria de fotos.
create table if not exists pet_photos (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  url text not null,
  caption text,
  taken_at timestamptz not null default now(),
  registered_by text,
  place text,
  period text,
  favorite boolean not null default false,
  created_at timestamptz not null default now()
);

-- Galeria de videos.
create table if not exists pet_videos (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  thumb_url text,
  video_url text,
  caption text,
  recorded_at timestamptz not null default now(),
  duration text,
  created_at timestamptz not null default now()
);

-- Carteira de vacinacao.
create table if not exists vaccines (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  name text not null,
  applied_date date,
  valid_until date,
  required boolean not null default false,
  attachment_url text,
  created_at timestamptz not null default now()
);

-- Plano/pacotes do tutor (resumo financeiro).
create table if not exists tutor_billing (
  tutor_id bigint primary key references tutors(id) on delete cascade,
  plan text,
  monthly_value numeric not null default 0,
  packages_left integer not null default 0,
  package_total integer not null default 0,
  next_due date,
  updated_at timestamptz not null default now()
);

-- Historico de pagamentos / notas.
create table if not exists invoices (
  id bigint generated by default as identity primary key,
  tutor_id bigint not null references tutors(id) on delete cascade,
  invoice_date date not null default current_date,
  description text not null,
  method text not null default 'PIX' check (method in ('PIX', 'Cartao', 'Boleto')),
  value numeric not null default 0,
  status text not null default 'Pendente' check (status in ('Pago', 'Pendente', 'Atrasado')),
  receipt_url text,
  created_at timestamptz not null default now()
);

-- Chat entre tutor e equipe (vinculado ao pet).
create table if not exists pet_messages (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  sender text not null default 'team' check (sender in ('tutor', 'team')),
  author text,
  body text not null,
  created_at timestamptz not null default now()
);

-- Notificacoes do tutor.
create table if not exists tutor_notifications (
  id bigint generated by default as identity primary key,
  tutor_id bigint not null references tutors(id) on delete cascade,
  icon text,
  body text not null,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

-- Relatorio diario.
create table if not exists daily_reports (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  report_date date not null default current_date,
  summary text,
  food text,
  hydration text,
  rest text,
  social text,
  mood text,
  occurrences text,
  responsible text,
  created_at timestamptz not null default now(),
  unique (pet_id, report_date)
);

-- Conquistas / medalhas.
create table if not exists pet_achievements (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  icon text,
  title text not null,
  description text,
  earned boolean not null default false,
  earned_at date,
  created_at timestamptz not null default now()
);

-- Linha do tempo da vida (momentos marcantes).
create table if not exists life_moments (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  icon text,
  title text not null,
  moment_date text,
  description text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

-- Historico de peso.
create table if not exists pet_weights (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  label text not null,
  weight numeric not null,
  recorded_on date,
  created_at timestamptz not null default now()
);

-- Resumos / insights gerados pela IA.
create table if not exists ai_insights (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references pets(id) on delete cascade,
  period text not null default 'Semana',
  body text not null,
  created_at timestamptz not null default now()
);

-- Avisos/comunicados gerais da creche.
create table if not exists announcements (
  id bigint generated by default as identity primary key,
  icon text,
  title text not null,
  body text,
  published_at timestamptz not null default now()
);

-- Indices
create index if not exists timeline_events_pet_idx on timeline_events(pet_id, event_date);
create index if not exists pet_photos_pet_idx on pet_photos(pet_id);
create index if not exists pet_videos_pet_idx on pet_videos(pet_id);
create index if not exists vaccines_pet_idx on vaccines(pet_id);
create index if not exists invoices_tutor_idx on invoices(tutor_id);
create index if not exists pet_messages_pet_idx on pet_messages(pet_id, created_at);
create index if not exists tutor_notifications_tutor_idx on tutor_notifications(tutor_id, read);
create index if not exists daily_reports_pet_idx on daily_reports(pet_id, report_date);
create index if not exists app_users_tutor_id_idx on app_users(tutor_id);

-- RLS (nega anon; service role ignora). Igual ao restante do schema.
alter table pet_presence        enable row level security;
alter table pet_traits          enable row level security;
alter table timeline_events     enable row level security;
alter table pet_photos          enable row level security;
alter table pet_videos          enable row level security;
alter table vaccines            enable row level security;
alter table tutor_billing       enable row level security;
alter table invoices            enable row level security;
alter table pet_messages        enable row level security;
alter table tutor_notifications enable row level security;
alter table daily_reports       enable row level security;
alter table pet_achievements    enable row level security;
alter table life_moments        enable row level security;
alter table pet_weights         enable row level security;
alter table ai_insights         enable row level security;
alter table announcements       enable row level security;

-- =====================================================================
-- 9. SEED - usuario TUTOR (login da Area do Tutor)
--    Login: mariana@email.com  /  Thor@2026
--    Vinculado ao cadastro de tutor "Mariana Alves".
-- =====================================================================

insert into app_users (name, email, role, password_salt, password_hash, is_active, tutor_id)
select
  'Mariana Alves',
  'mariana@email.com',
  'tutor',
  'scoltcia-mariana-2026',
  'cc9878680a870359e662fa92aa421f82ac764911bc92f2e5daaa6eff4118538175c63ec3c472ef7d0133a6040fd609d8dea2ece43018f83e1900fc88b27415a0',
  true,
  (select id from tutors where email = 'mariana@email.com')
on conflict (email) do update set
  role = 'tutor',
  password_salt = excluded.password_salt,
  password_hash = excluded.password_hash,
  is_active = true,
  tutor_id = excluded.tutor_id;

-- =====================================================================
-- 10. SEED - dados de exemplo do pet "Thor" (Area do Tutor)
--     Idempotente. Cria o Thor para a Mariana e popula o portal.
-- =====================================================================

-- Pet Thor
insert into pets (tutor_id, name, breed, size, sex, weight, birth_date, behavior, allergies, food_restrictions, medications, important_notes, veterinarian, photo_url, microchip, neutered, cover_url)
select
  t.id, 'Thor', 'Golden Retriever', 'Grande', 'Macho', 28.4, date '2022-03-12',
  'Muito sociavel e brincalhao',
  'Frango, Picada de pulga',
  'Sem petiscos industrializados',
  'Antialergico 1x ao dia (manha)',
  'Tem displasia leve no quadril - evitar saltos altos.',
  'Dra. Carina Mendes - Clinica VidaPet',
  'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?auto=format&fit=crop&w=400&q=85',
  '982000412345678', true,
  'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1200&q=85'
from tutors t
where t.email = 'mariana@email.com'
  and not exists (select 1 from pets p where p.name = 'Thor' and p.tutor_id = t.id);

insert into pet_tutors (pet_id, tutor_id)
select p.id, p.tutor_id from pets p where p.name = 'Thor' and p.tutor_id is not null
on conflict do nothing;

-- Helper implicito: a partir daqui usamos (select id from pets where name='Thor' ...) como :thor
-- Presenca
insert into pet_presence (pet_id, present, location, activity, last_visit)
select p.id, true, 'Piscina', 'Brincando na piscina', 'Ontem'
from pets p where p.name = 'Thor'
on conflict (pet_id) do nothing;

-- Personalidade
insert into pet_traits (pet_id, emoji, label)
select p.id, v.emoji, v.label
from pets p
cross join (values
  ('🎾','Ama brincar de bolinha'),
  ('🌧️','Nao gosta de chuva'),
  ('🎆','Tem medo de fogos'),
  ('🏊','Gosta muito de agua'),
  ('😴','Prefere descansar depois do almoco'),
  ('🤝','Muito sociavel com outros pets')
) as v(emoji, label)
where p.name = 'Thor'
  and not exists (select 1 from pet_traits pt where pt.pet_id = p.id);

-- Timeline do dia
insert into timeline_events (pet_id, event_time, icon, title, detail, type)
select p.id, v.t, v.icon, v.title, v.detail, v.type
from pets p
cross join (values
  ('08:02','🚪','Check-in realizado','Thor chegou animado e foi recebido pela equipe.','checkin'),
  ('08:20','🐶','Conheceu dois novos amigos','Fez amizade com a Mel e o Bento no parquinho.','social'),
  ('09:15','🏊','Brincou na piscina','Mergulhou atras da bolinha por 20 minutos.','play'),
  ('10:05','🍖','Recebeu petisco','Petisco natural de batata-doce.','food'),
  ('11:40','📸','Foto adicionada','Nova foto na galeria do dia.','photo'),
  ('13:00','🍽️','Almocou normalmente','Comeu toda a racao sem restricoes.','food'),
  ('14:30','💤','Descansou','Soneca tranquila na sala climatizada.','rest'),
  ('16:10','🎾','Brincou novamente','Sessao de recreacao monitorada com o grupo.','play'),
  ('17:00','🏠','Check-out realizado','Dia completo! Thor foi embora cansado e feliz.','checkout')
) as v(t, icon, title, detail, type)
where p.name = 'Thor'
  and not exists (select 1 from timeline_events te where te.pet_id = p.id);

-- Fotos
insert into pet_photos (pet_id, url, caption, registered_by, place, period, favorite)
select p.id, v.url, v.caption, v.by, v.place, v.period, v.fav
from pets p
cross join (values
  ('https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=700&q=85','Correria no jardim 🌿','Equipe Scolt','Playground','Hoje',true),
  ('https://images.unsplash.com/photo-1561037404-61cd46aa615b?auto=format&fit=crop&w=700&q=85','Caca a bolinha 🎾','Cuidadora Bia','Piscina','Hoje',false),
  ('https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?auto=format&fit=crop&w=700&q=85','Hora da soneca 😴','Equipe Scolt','Sala climatizada','Hoje',true),
  ('https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=700&q=85','Novos amigos 🐾','Cuidador Leo','Parque','Esta semana',false),
  ('https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=700&q=85','Banho relaxante 🛁','Equipe Banho','Banho e Tosa','Esta semana',false),
  ('https://images.unsplash.com/photo-1601979031925-424e53b6caaa?auto=format&fit=crop&w=700&q=85','Olhar de campeao 🏅','Equipe Scolt','Playground','Este mes',true)
) as v(url, caption, by, place, period, fav)
where p.name = 'Thor'
  and not exists (select 1 from pet_photos pp where pp.pet_id = p.id);

-- Videos
insert into pet_videos (pet_id, thumb_url, caption, duration)
select p.id, v.thumb, v.caption, v.dur
from pets p
cross join (values
  ('https://images.unsplash.com/photo-1546238232-20216dec9f72?auto=format&fit=crop&w=700&q=85','Mergulho na piscina','0:24'),
  ('https://images.unsplash.com/photo-1568572933382-74d440642117?auto=format&fit=crop&w=700&q=85','Recreacao em grupo','0:41'),
  ('https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&w=700&q=85','Brincadeira com a Mel','0:33')
) as v(thumb, caption, dur)
where p.name = 'Thor'
  and not exists (select 1 from pet_videos pv where pv.pet_id = p.id);

-- Vacinas
insert into vaccines (pet_id, name, applied_date, valid_until, required)
select p.id, v.name, v.applied::date, v.valid::date, v.req
from pets p
cross join (values
  ('V10 (Polivalente)','2025-04-15','2026-04-15',true),
  ('Antirrabica','2025-06-20','2026-07-20',true),
  ('Giardia','2025-01-10','2026-01-10',false),
  ('Gripe Canina','2025-05-05','2026-05-05',false)
) as v(name, applied, valid, req)
where p.name = 'Thor'
  and not exists (select 1 from vaccines vc where vc.pet_id = p.id);

-- Financeiro (plano + faturas)
insert into tutor_billing (tutor_id, plan, monthly_value, packages_left, package_total, next_due)
select t.id, 'Day Care - Plano Mensal', 780, 4, 10, date '2026-07-05'
from tutors t where t.email = 'mariana@email.com'
on conflict (tutor_id) do nothing;

insert into invoices (tutor_id, invoice_date, description, method, value, status)
select t.id, v.d::date, v.descr, v.method, v.val, 'Pago'
from tutors t
cross join (values
  ('2026-06-05','Mensalidade Junho','PIX',780),
  ('2026-05-05','Mensalidade Maio','Cartao',780),
  ('2026-05-22','Banho e Tosa avulso','PIX',120),
  ('2026-04-05','Mensalidade Abril','Boleto',780)
) as v(d, descr, method, val)
where t.email = 'mariana@email.com'
  and not exists (select 1 from invoices i where i.tutor_id = t.id);

-- Mensagens
insert into pet_messages (pet_id, sender, author, body, created_at)
select p.id, v.sender, v.author, v.body, now() - (v.mins || ' minutes')::interval
from pets p
cross join (values
  ('team','Equipe Scolt','Bom dia, Mariana! O Thor chegou super animado hoje 🐶', 120),
  ('tutor','Voce','Que otimo! Ele dormiu pouco ontem, fica de olho 😅', 110),
  ('team','Equipe Scolt','Pode deixar! Ja separamos a sala climatizada pra soneca dele.', 108),
  ('team','Cuidadora Bia','Ele acabou de brincar na piscina, mandei um video na galeria 🏊', 60),
  ('tutor','Voce','Amei! Obrigada pelo carinho de sempre 💛', 55)
) as v(sender, author, body, mins)
where p.name = 'Thor'
  and not exists (select 1 from pet_messages pm where pm.pet_id = p.id);

-- Notificacoes
insert into tutor_notifications (tutor_id, icon, body, read)
select t.id, v.icon, v.body, v.read
from tutors t
cross join (values
  ('📸','Nova foto do Thor adicionada.', false),
  ('🏊','Thor esta brincando na piscina.', false),
  ('🍖','Thor acabou de receber um petisco.', false),
  ('🐶','Thor entrou na creche.', true),
  ('❤️','Seu relatorio diario esta pronto.', true)
) as v(icon, body, read)
where t.email = 'mariana@email.com'
  and not exists (select 1 from tutor_notifications tn where tn.tutor_id = t.id);

-- Relatorio diario
insert into daily_reports (pet_id, report_date, summary, food, hydration, rest, social, mood, occurrences, responsible)
select p.id, current_date,
  'Thor teve um dia excelente! Muito ativo pela manha, socializou bem e descansou no periodo da tarde.',
  'Comeu 100% da racao no almoco. Aceitou bem o petisco natural.',
  'Boa hidratacao ao longo do dia.',
  'Soneca de 1h40 na sala climatizada.',
  'Interagiu com 6 pets diferentes. Destaque para Mel e Bento.',
  'Alegre e brincalhao',
  'Nenhuma ocorrencia.',
  'Bia Camargo'
from pets p where p.name = 'Thor'
on conflict (pet_id, report_date) do nothing;

-- Conquistas
insert into pet_achievements (pet_id, icon, title, description, earned)
select p.id, v.icon, v.title, v.descr, v.earned
from pets p
cross join (values
  ('🏅','Primeira Visita','O comeco de tudo!',true),
  ('🎉','10 Visitas','Ja virou de casa.',true),
  ('🤝','Sociavel','Fez 20+ amigos.',true),
  ('🏊','Nadador','Ama a piscina.',true),
  ('⭐','Bom Comportamento','Exemplo de educacao.',true),
  ('💛','Melhor Amigo','Parceiro inseparavel.',false),
  ('🎖️','Veterano da Creche','100 visitas completas.',false),
  ('🦴','Comilao','Nunca recusa comida.',true)
) as v(icon, title, descr, earned)
where p.name = 'Thor'
  and not exists (select 1 from pet_achievements pa where pa.pet_id = p.id);

-- Linha do tempo da vida
insert into life_moments (pet_id, icon, title, moment_date, description, sort_order)
select p.id, v.icon, v.title, v.d, v.descr, v.ord
from pets p
cross join (values
  ('🐾','Primeira visita','Mar 2024','Thor pisou na creche pela primeira vez.',1),
  ('🤝','Primeira amizade','Mar 2024','Conheceu a Mel, sua melhor amiga.',2),
  ('🛁','Primeiro banho','Abr 2024','Estreia no banho e tosa.',3),
  ('🎂','Aniversario de 2 anos','Mar 2024','Festinha com bolo de pet.',4),
  ('🎉','100a visita','Jan 2026','Marco de fidelidade!',5),
  ('🏊','Conquistou a piscina','Fev 2026','Perdeu o medo da agua.',6)
) as v(icon, title, d, descr, ord)
where p.name = 'Thor'
  and not exists (select 1 from life_moments lm where lm.pet_id = p.id);

-- Historico de peso
insert into pet_weights (pet_id, label, weight)
select p.id, v.label, v.w
from pets p
cross join (values
  ('Jan',27.1),('Fev',27.6),('Mar',27.9),('Abr',28.0),('Mai',28.2),('Jun',28.4)
) as v(label, w)
where p.name = 'Thor'
  and not exists (select 1 from pet_weights pw where pw.pet_id = p.id);

-- Insights da IA
insert into ai_insights (pet_id, period, body)
select p.id, v.period, v.body
from pets p
cross join (values
  ('Semana','Thor apresentou maior nivel de atividade nesta semana em comparacao as anteriores.'),
  ('Mes','Thor brincou com 12 pets diferentes durante o mes.'),
  ('Semana','Thor descansou menos do que sua media habitual - de olho no sono.'),
  ('Semana','Excelente socializacao: ele liderou as brincadeiras em grupo.')
) as v(period, body)
where p.name = 'Thor'
  and not exists (select 1 from ai_insights ai where ai.pet_id = p.id);

-- Avisos gerais
insert into announcements (icon, title, body)
select v.icon, v.title, v.body
from (values
  ('📢','Feriado de Corpus Christi','Funcionaremos em horario reduzido: 8h as 14h.'),
  ('💉','Campanha de vacinacao','Traga a carteirinha atualizada ate 30/06.')
) as v(icon, title, body)
where not exists (select 1 from announcements);
